version: '3'

services:
  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.44.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  snmp-exporter:
    image: quay.io/prometheus/snmp-exporter
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
      - /opt/docker-persist/snmp-exporter:/etc/snmp_exporter
    ports:
      - 9116:9116
      - 116:116/udp
    restart: always
    command: --config.file=/etc/snmp_exporter/snmp.yml

