version: '3'

services:
  grafana:
    image: grafana/grafana:9.5.2-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana-storage:/var/lib/grafana

  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-storage:/var/lib/influxdb

  telegraf:
    image: telegraf:1.26.3
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

