global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'snmp'
    metrics_path: /snmp
    static_configs:
      - targets: ['localhost:9116']

- job_name: 'snmp'
  metrics_path: /snmp
  static_configs:
    - targets:
        - '192.168.15.6:161'  # Dirección IP del dispositivo SNMP
      params:
        module: [default]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: localhost:9116  # Dirección y puerto del SNMP Exporter


